name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository code
        uses: action/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies with Poetry
        run: |
          poetry install --no-interaction --with dev

      - name: Run Ruff formatter check
        run: |
          poetry run ruff format . --check

      - name: Run Ruff linter check
        run: |
          poetry run ruff check .

      - name: Run Mypy check
        run: |
          poetry run mypy .

      - name: Run tests and generate coverage report
        run: |
          poetry run pytest --cov-report=lcov tests/

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
